### This file acts as a Contract showing all available routes
### for the frontend as well as a set of tests for our backends.

### CREATE ACCOUNT
POST  http://localhost:13000/auth/register
Content-Type: application/json

{
  "firstName": "User 6",
  "lastName": "Wassup",
  "email": "duykhang2302@gmail.com",
  "password": "testSep18@example.com"
}

### LOGIN 
POST  http://localhost:13000/auth/login
Content-Type: application/json

{
  "email": "testSep9@example.com",
  "password": "testSep9@example.com"
}
###

### LOGIN SUCCESS 
POST  http://localhost:13000/auth/login/email
Content-Type: application/json

{
  "email": "user3@example.com",
  "password": "your-password"
}
###
### LOGIN FAILED 
POST  http://localhost:13000/auth/login/email
Content-Type: application/json

{
  "email": "user5@example.com",
  "password": "your1-password"
}
###
### Login/ Register with Google: http://localhost:13000/auth/google

### GET USER BY ID
GET http://localhost:13000/users/get?id=6c3d889c-7d44-4b4f-a28b-7f38606d4f21

###

### UPDATE PASSWORD
PATCH http://localhost:13000/users/update-password
Content-Type: application/json

{
  "update_password" : "my-password-this-time" 
}

### UPDATE USER
PATCH http://localhost:13000/users/update
Content-Type: application/json

{
  "fieldsToUpdate" : {
    "firstName" : "New First Name",
    "lastName" : "New Last Name"
  }
}


### DELETE USER
DELETE  http://localhost:13000/users/delete
Content-Type: application/json

{
  "email" : "duykhang2302@gmail.com"
}

### LOGOUT USER
POST http://localhost:13000/auth/logout
Content-Type: application/json

### GET ALL SPORTS
GET  http://localhost:13000/utils/getAllSports
Content-Type: application/json


### CREATE A NEW POST:
POST http://localhost:13000/posts/create
Content-Type: application/json

{
  "title": "Basketball Game",
  "description": "A fun pick up",
  "creatorId": "66d2668f-5408-412b-8c3a-d45fbe7733e1",
  "location": "400 Westcroft Drive, Waterloo",
  "eventDate": "2023-09-20 17:12:28.418 -0400",
  "eventType": "GAME"
} 
### GET POST BY POST ID
GET http://localhost:13000/posts/getPostById?id=b2687d64-7b64-4161-99b3-8afb71f080cb
###

### DELETE
DELETE  http://localhost:13000/posts/delete
Content-Type: application/json

{
  "id": "3069c1ae-7b19-4d72-9e50-040fafaa422a"
}

### UPDATE POST
PATCH  http://localhost:13000/posts/update
Content-Type: application/json

{
  "id": "fd071664-250f-4360-93cc-8e8c54f51e1f",
  "fieldsToUpdate" : {
    "title" : "jfnweiognfwoenf"
  }

}

### GET
GET  http://localhost:13000/posts/getPostByLocation
Content-Type: application/json

{
  "longtitude" : -80.432953,
  "latitude" : 143.469666
}
